// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs ext4_simple.go

package main

type ext4Inode struct {
	Mode		uint16
	Uid		uint16
	Size_lo		uint32
	Atime		uint32
	Ctime		uint32
	Mtime		uint32
	Dtime		uint32
	Gid		uint16
	Links_count	uint16
	Blocks_lo	uint32
	Flags		uint32
	Osd1		[4]byte
	Block		[15]uint32
	Generation	uint32
	File_acl_lo	uint32
	Size_high	uint32
	Obso_faddr	uint32
	Osd2		[12]byte
	Extra_isize	uint16
	Checksum_hi	uint16
	Ctime_extra	uint32
	Mtime_extra	uint32
	Atime_extra	uint32
	Crtime		uint32
	Crtime_extra	uint32
	Version_hi	uint32
	Projid		uint32
}
type ext4SuperBlock struct {
	Inodes_count		uint32
	Blocks_count_lo		uint32
	R_blocks_count_lo	uint32
	Free_blocks_count_lo	uint32
	Free_inodes_count	uint32
	First_data_block	uint32
	Log_block_size		uint32
	Log_cluster_size	uint32
	Blocks_per_group	uint32
	Clusters_per_group	uint32
	Inodes_per_group	uint32
	Mtime			uint32
	Wtime			uint32
	Mnt_count		uint16
	Max_mnt_count		uint16
	Magic			uint16
	State			uint16
	Errors			uint16
	Minor_rev_level		uint16
	Lastcheck		uint32
	Checkinterval		uint32
	Creator_os		uint32
	Rev_level		uint32
	Def_resuid		uint16
	Def_resgid		uint16
	First_ino		uint32
	Inode_size		uint16
	Block_group_nr		uint16
	Feature_compat		uint32
	Feature_incompat	uint32
	Feature_ro_compat	uint32
	Uuid			[16]uint8
	Volume_name		[16]int8
	Last_mounted		[64]int8
	Algorithm_usage_bitmap	uint32
	Prealloc_blocks		uint8
	Prealloc_dir_blocks	uint8
	Reserved_gdt_blocks	uint16
	Journal_uuid		[16]uint8
	Journal_inum		uint32
	Journal_dev		uint32
	Last_orphan		uint32
	Hash_seed		[4]uint32
	Def_hash_version	uint8
	Jnl_backup_type		uint8
	Desc_size		uint16
	Default_mount_opts	uint32
	First_meta_bg		uint32
	Mkfs_time		uint32
	Jnl_blocks		[17]uint32
	Blocks_count_hi		uint32
	R_blocks_count_hi	uint32
	Free_blocks_count_hi	uint32
	Min_extra_isize		uint16
	Want_extra_isize	uint16
	Flags			uint32
	Raid_stride		uint16
	Mmp_update_interval	uint16
	Mmp_block		uint64
	Raid_stripe_width	uint32
	Log_groups_per_flex	uint8
	Checksum_type		uint8
	Encryption_level	uint8
	Reserved_pad		uint8
	Kbytes_written		uint64
	Snapshot_inum		uint32
	Snapshot_id		uint32
	Snapshot_r_blocks_count	uint64
	Snapshot_list		uint32
	Error_count		uint32
	First_error_time	uint32
	First_error_ino		uint32
	First_error_block	uint64
	First_error_func	[32]uint8
	First_error_line	uint32
	Last_error_time		uint32
	Last_error_ino		uint32
	Last_error_line		uint32
	Last_error_block	uint64
	Last_error_func		[32]uint8
	Mount_opts		[64]uint8
	Usr_quota_inum		uint32
	Grp_quota_inum		uint32
	Overhead_clusters	uint32
	Backup_bgs		[2]uint32
	Encrypt_algos		[4]uint8
	Encrypt_pw_salt		[16]uint8
	Lpf_ino			uint32
	Prj_quota_inum		uint32
	Checksum_seed		uint32
	Wtime_hi		uint8
	Mtime_hi		uint8
	Mkfs_time_hi		uint8
	Lastcheck_hi		uint8
	First_error_time_hi	uint8
	Last_error_time_hi	uint8
	Pad			[2]uint8
	Encoding		uint16
	Encoding_flags		uint16
	Reserved		[95]uint32
	Checksum		uint32
}
type ext4GroupDesc struct {
	Block_bitmap_lo		uint32
	Inode_bitmap_lo		uint32
	Inode_table_lo		uint32
	Free_blocks_count_lo	uint16
	Free_inodes_count_lo	uint16
	Used_dirs_count_lo	uint16
	Flags			uint16
	Exclude_bitmap_lo	uint32
	Block_bitmap_csum_lo	uint16
	Inode_bitmap_csum_lo	uint16
	Itable_unused_lo	uint16
	Checksum		uint16
	Block_bitmap_hi		uint32
	Inode_bitmap_hi		uint32
	Inode_table_hi		uint32
	Free_blocks_count_hi	uint16
	Free_inodes_count_hi	uint16
	Used_dirs_count_hi	uint16
	Itable_unused_hi	uint16
	Exclude_bitmap_hi	uint32
	Block_bitmap_csum_hi	uint16
	Inode_bitmap_csum_hi	uint16
	Reserved		uint32
}
type ext4Extent struct {
	Block		uint32
	Len		uint16
	Start_hi	uint16
	Start_lo	uint32
}
type ext4ExtentIdx struct {
	Block	uint32
	Leaf_lo	uint32
	Leaf_hi	uint16
	Unused	uint16
}
type ext4ExtentHeader struct {
	Magic		uint16
	Entries		uint16
	Max		uint16
	Depth		uint16
	Generation	uint32
}
type ext4DirEntry struct {
	Inode		uint32
	Rec_len		uint16
	Name_len	uint16
	Name		[255]int8
	Pad_cgo_0	[1]byte
}
type ext4DirEntry_2 struct {
	Inode		uint32
	Rec_len		uint16
	Name_len	uint8
	File_type	uint8
	Name		[255]int8
	Pad_cgo_0	[1]byte
}

const (
	EXT4_SUPER_MAGIC			= 0xef53
	EXT4_FEATURE_COMPAT_DIR_PREALLOC	= 0x1
	EXT4_FEATURE_COMPAT_IMAGIC_INODES	= 0x2
	EXT4_FEATURE_COMPAT_HAS_JOURNAL		= 0x4
	EXT4_FEATURE_COMPAT_EXT_ATTR		= 0x8
	EXT4_FEATURE_COMPAT_RESIZE_INODE	= 0x10
	EXT4_FEATURE_COMPAT_DIR_INDEX		= 0x20
	EXT4_FEATURE_COMPAT_SPARSE_SUPER2	= 0x200
	EXT4_FEATURE_RO_COMPAT_SPARSE_SUPER	= 0x1
	EXT4_FEATURE_RO_COMPAT_LARGE_FILE	= 0x2
	EXT4_FEATURE_RO_COMPAT_BTREE_DIR	= 0x4
	EXT4_FEATURE_RO_COMPAT_HUGE_FILE	= 0x8
	EXT4_FEATURE_RO_COMPAT_GDT_CSUM		= 0x10
	EXT4_FEATURE_RO_COMPAT_DIR_NLINK	= 0x20
	EXT4_FEATURE_RO_COMPAT_EXTRA_ISIZE	= 0x40
	EXT4_FEATURE_RO_COMPAT_QUOTA		= 0x100
	EXT4_FEATURE_RO_COMPAT_BIGALLOC		= 0x200
	EXT4_FEATURE_RO_COMPAT_METADATA_CSUM	= 0x400
	EXT4_FEATURE_RO_COMPAT_READONLY		= 0x1000
	EXT4_FEATURE_RO_COMPAT_PROJECT		= 0x2000
	EXT4_FEATURE_RO_COMPAT_VERITY		= 0x8000
	EXT4_FEATURE_INCOMPAT_COMPRESSION	= 0x1
	EXT4_FEATURE_INCOMPAT_FILETYPE		= 0x2
	EXT4_FEATURE_INCOMPAT_RECOVER		= 0x4
	EXT4_FEATURE_INCOMPAT_JOURNAL_DEV	= 0x8
	EXT4_FEATURE_INCOMPAT_META_BG		= 0x10
	EXT4_FEATURE_INCOMPAT_EXTENTS		= 0x40
	EXT4_FEATURE_INCOMPAT_64BIT		= 0x80
	EXT4_FEATURE_INCOMPAT_MMP		= 0x100
	EXT4_FEATURE_INCOMPAT_FLEX_BG		= 0x200
	EXT4_FEATURE_INCOMPAT_EA_INODE		= 0x400
	EXT4_FEATURE_INCOMPAT_DIRDATA		= 0x1000
	EXT4_FEATURE_INCOMPAT_CSUM_SEED		= 0x2000
	EXT4_FEATURE_INCOMPAT_LARGEDIR		= 0x4000
	EXT4_FEATURE_INCOMPAT_INLINE_DATA	= 0x8000
	EXT4_FEATURE_INCOMPAT_ENCRYPT		= 0x10000
	EXT4_FEATURE_INCOMPAT_CASEFOLD		= 0x20000
	EXT4_SECRM_FL				= 0x1
	EXT4_UNRM_FL				= 0x2
	EXT4_COMPR_FL				= 0x4
	EXT4_SYNC_FL				= 0x8
	EXT4_IMMUTABLE_FL			= 0x10
	EXT4_APPEND_FL				= 0x20
	EXT4_NODUMP_FL				= 0x40
	EXT4_NOATIME_FL				= 0x80
	EXT4_DIRTY_FL				= 0x100
	EXT4_COMPRBLK_FL			= 0x200
	EXT4_NOCOMPR_FL				= 0x400
	EXT4_ENCRYPT_FL				= 0x800
	EXT4_INDEX_FL				= 0x1000
	EXT4_IMAGIC_FL				= 0x2000
	EXT4_JOURNAL_DATA_FL			= 0x4000
	EXT4_NOTAIL_FL				= 0x8000
	EXT4_DIRSYNC_FL				= 0x10000
	EXT4_TOPDIR_FL				= 0x20000
	EXT4_HUGE_FILE_FL			= 0x40000
	EXT4_EXTENTS_FL				= 0x80000
	EXT4_VERITY_FL				= 0x100000
	EXT4_EA_INODE_FL			= 0x200000
	EXT4_EOFBLOCKS_FL			= 0x400000
	EXT4_INLINE_DATA_FL			= 0x10000000
	EXT4_PROJINHERIT_FL			= 0x20000000
	EXT4_CASEFOLD_FL			= 0x40000000
	EXT4_RESERVED_FL			= 0x80000000
	EXT4_NDIR_BLOCKS			= 0xc
	EXT4_IND_BLOCK				= 0xc
	EXT4_DIND_BLOCK				= 0xd
	EXT4_TIND_BLOCK				= 0xe
	EXT4_N_BLOCKS				= 0xf
	EXT4_S_ERR_START			= 0x194
	EXT4_S_ERR_END				= 0x200
	S_IFMT					= 0xf000
	S_IFSOCK				= 0xc000
	S_IFLNK					= 0xa000
	S_IFREG					= 0x8000
	S_IFBLK					= 0x6000
	S_IFDIR					= 0x4000
	S_IFCHR					= 0x2000
	S_IFIFO					= 0x1000
	S_ISUID					= 0x800
	S_ISGID					= 0x400
	S_ISVTX					= 0x200
	EXT4_FT_UNKNOWN				= 0x0
	EXT4_FT_REG_FILE			= 0x1
	EXT4_FT_DIR				= 0x2
	EXT4_FT_CHRDEV				= 0x3
	EXT4_FT_BLKDEV				= 0x4
	EXT4_FT_FIFO				= 0x5
	EXT4_FT_SOCK				= 0x6
	EXT4_FT_SYMLINK				= 0x7
	EXT4_FT_MAX				= 0x8
	S_SHIFT					= 0xc
	BLOCK_SIZE_BITS				= 0xa
	BLOCK_SIZE				= 0x400
	EXT4_BAD_INO				= 0x1
	EXT4_ROOT_INO				= 0x2
	EXT4_USR_QUOTA_INO			= 0x3
	EXT4_GRP_QUOTA_INO			= 0x4
	EXT4_BOOT_LOADER_INO			= 0x5
	EXT4_UNDEL_DIR_INO			= 0x6
	EXT4_RESIZE_INO				= 0x7
	EXT4_JOURNAL_INO			= 0x8
	EXT4_EXT_MAGIC				= 0xf30a
	EXT4_MAX_EXTENT_DEPTH			= 0x5
	EXT4_NAME_LEN				= 0xff
)
